"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Wand2, Cpu, Copy, Check, RefreshCw } from "lucide-react"

const EXAMPLE_OUTPUTS: Record<string, string> = {
  "task-planner": `🤖 TaskPlanner Agent — System Architecture Blueprint
═══════════════════════════════════════════════════
CORE LOOP
  Input → Intent Parser → Task Graph Builder → Executor
      ↘ Memory (episodic + semantic)
      ↘ Tool Dispatcher

LLM PROVIDERS
  Primary:   anthropic/claude-opus
  Fallback:  openai/gpt-4o

TOOLS REGISTRY
  • plan_task         Create structured task trees
  • assign_subtask    Delegate to sub-agents
  • track_progress    Monitor execution state
  • reflect           Self-evaluate and replan

MEMORY LAYERS
  Episodic  → Session history (last 20 turns)
  Semantic  → Vector store (task patterns)
  Working   → Current task graph in context

DESIGN PRINCIPLES
  ✦ Hierarchical decomposition
  ✦ Reflection after each major step
  ✦ Fail-fast with graceful degradation

CHANNELS
  REST API · WebSocket (real-time updates) · Webhook callbacks`,

  "data-analyst": `🤖 DataAnalyst Agent — System Architecture Blueprint
═══════════════════════════════════════════════════
CORE LOOP
  Query → Schema Loader → SQL/Python Generator → Executor → Formatter
      ↘ Chart Generator (matplotlib / d3)
      ↘ Insight Summarizer

LLM PROVIDERS
  Primary:   openai/gpt-4o
  Code:      deepseek/deepseek-coder

TOOLS REGISTRY
  • run_sql            Execute queries on connected DBs
  • run_python         Execute pandas / numpy code
  • generate_chart     Produce visualizations
  • summarize_insight  Natural language summary

MEMORY LAYERS
  Schema Cache  → Table metadata + column types
  Query History → Prior queries (session)
  Result Cache  → Dedup expensive computations

DESIGN PRINCIPLES
  ✦ Always validate SQL before execution
  ✦ Show work: return intermediate steps
  ✦ Charts over tables when trend > 3 points

CHANNELS
  Slack · Jupyter Notebook · REST API · CSV Upload`,

  "": `🤖 CustomAgent — System Architecture Blueprint
═══════════════════════════════════════════════════
CORE LOOP
  Message → Context Builder → LLM → Tool Dispatcher → Response
      ↘ Memory Store (session + long-term)

LLM PROVIDERS
  Primary:   (configure your provider)
  Fallback:  (optional fallback)

TOOLS REGISTRY
  • tool_one   Description of first tool
  • tool_two   Description of second tool
  • tool_three Description of third tool

MEMORY LAYERS
  Session   → Conversation history
  Long-term → Compressed summaries + key facts

DESIGN PRINCIPLES
  ✦ Principle one
  ✦ Principle two
  ✦ Principle three

CHANNELS
  (configure your channels)`,
}

function generateBlueprint(
  name: string,
  purpose: string,
  providers: string,
  tools: string,
  channels: string
): string {
  const toolList = tools
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean)
    .map((t) => `  • ${t.padEnd(20)} Auto-generated tool`)
    .join("\n")

  const providerList = providers
    .split(",")
    .map((p) => p.trim())
    .filter(Boolean)

  return `🤖 ${name || "MyAgent"} — System Architecture Blueprint
${"═".repeat(52)}
PURPOSE
  ${purpose || "General-purpose AI agent"}

CORE LOOP
  Input → Intent Parser → LLM → Tool Dispatcher → Response
      ↘ Memory (session + long-term)
      ↘ Context Builder

LLM PROVIDERS
  Primary:   ${providerList[0] || "openai/gpt-4o"}
  ${providerList[1] ? `Fallback:  ${providerList[1]}` : ""}

TOOLS REGISTRY
${toolList || "  • (no tools configured)"}

MEMORY LAYERS
  Session   → Conversation history (last 20 turns)
  Long-term → Compressed episodic + semantic store
  Working   → Current task context

DESIGN PRINCIPLES
  ✦ Modular and composable
  ✦ Fail gracefully with meaningful errors
  ✦ Reflection loop on complex tasks
  ✦ Async-first I/O

CHANNELS
  ${channels || "(configure your channels)"}

GENERATED BY Galatea AI Blueprint Studio`
}

export function BlueprintGenerator() {
  const [name, setName] = useState("")
  const [purpose, setPurpose] = useState("")
  const [providers, setProviders] = useState("")
  const [tools, setTools] = useState("")
  const [channels, setChannels] = useState("")
  const [output, setOutput] = useState(EXAMPLE_OUTPUTS[""])
  const [copied, setCopied] = useState(false)
  const [generating, setGenerating] = useState(false)

  const handleGenerate = () => {
    setGenerating(true)
    setTimeout(() => {
      setOutput(generateBlueprint(name, purpose, providers, tools, channels))
      setGenerating(false)
    }, 800)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExample = (key: string) => {
    setOutput(EXAMPLE_OUTPUTS[key] || EXAMPLE_OUTPUTS[""])
    if (key === "task-planner") {
      setName("TaskPlanner")
      setPurpose("Break user goals into structured task trees and delegate to sub-agents")
      setProviders("anthropic/claude-opus, openai/gpt-4o")
      setTools("plan_task, assign_subtask, track_progress, reflect")
      setChannels("REST API, WebSocket, Webhook")
    } else if (key === "data-analyst") {
      setName("DataAnalyst")
      setPurpose("Analyze databases, run queries, generate charts and insights")
      setProviders("openai/gpt-4o, deepseek/deepseek-coder")
      setTools("run_sql, run_python, generate_chart, summarize_insight")
      setChannels("Slack, Jupyter, REST API")
    }
  }

  return (
    <section id="blueprint" className="py-24 relative">
      {/* Background accent */}
      <div className="absolute inset-0 bg-gradient-radial from-purple-500/5 via-transparent to-transparent" />

      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-14">
          <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 rounded-full px-4 py-1.5 mb-5 text-sm text-gray-300">
            <Wand2 size={14} className="text-purple-400" />
            Blueprint Studio
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Generate Your Agent&apos;s <span className="text-gradient">Blueprint</span>
          </h2>
          <p className="text-gray-400 max-w-xl mx-auto">
            Describe your agent and get a structured architecture document you can publish to the registry, share with peers, or use as a spec for building.
          </p>
        </div>

        {/* Example presets */}
        <div className="flex flex-wrap justify-center gap-3 mb-10">
          {[
            { key: "task-planner", label: "🗂️ Task Planner" },
            { key: "data-analyst", label: "📊 Data Analyst" },
            { key: "", label: "⚡ Start fresh" },
          ].map(({ key, label }) => (
            <button
              key={key || "fresh"}
              onClick={() => handleExample(key)}
              className="text-sm bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 rounded-full px-4 py-1.5 text-gray-300 transition-all"
            >
              {label}
            </button>
          ))}
        </div>

        <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          {/* Inputs */}
          <div className="space-y-4">
            <div>
              <label className="text-xs text-gray-500 uppercase tracking-widest mb-2 block">Agent Name</label>
              <Input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. TaskPlanner, DataBot, Navigator..."
                className="bg-white/5 border-white/10 text-white placeholder:text-gray-600"
              />
            </div>
            <div>
              <label className="text-xs text-gray-500 uppercase tracking-widest mb-2 block">Purpose / Role</label>
              <textarea
                value={purpose}
                onChange={(e) => setPurpose(e.target.value)}
                placeholder="What does this agent do? What problem does it solve?"
                rows={3}
                className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-2.5 text-white placeholder:text-gray-600 text-sm focus:outline-none focus:ring-2 focus:ring-aura-blue/40 resize-none"
              />
            </div>
            <div>
              <label className="text-xs text-gray-500 uppercase tracking-widest mb-2 block">LLM Providers (comma-separated)</label>
              <Input
                value={providers}
                onChange={(e) => setProviders(e.target.value)}
                placeholder="e.g. anthropic/claude-opus, openai/gpt-4o"
                className="bg-white/5 border-white/10 text-white placeholder:text-gray-600"
              />
            </div>
            <div>
              <label className="text-xs text-gray-500 uppercase tracking-widest mb-2 block">Tools (comma-separated)</label>
              <Input
                value={tools}
                onChange={(e) => setTools(e.target.value)}
                placeholder="e.g. web_search, run_code, send_email"
                className="bg-white/5 border-white/10 text-white placeholder:text-gray-600"
              />
            </div>
            <div>
              <label className="text-xs text-gray-500 uppercase tracking-widest mb-2 block">Channels</label>
              <Input
                value={channels}
                onChange={(e) => setChannels(e.target.value)}
                placeholder="e.g. Slack, REST API, Telegram"
                className="bg-white/5 border-white/10 text-white placeholder:text-gray-600"
              />
            </div>
            <Button
              variant="gradient"
              size="lg"
              className="w-full gap-2"
              onClick={handleGenerate}
              disabled={generating}
            >
              {generating ? (
                <><RefreshCw size={16} className="animate-spin" /> Generating...</>
              ) : (
                <><Wand2 size={16} /> Generate Blueprint</>
              )}
            </Button>
          </div>

          {/* Output */}
          <div className="relative">
            <div className="aura-card h-full min-h-[400px]">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-sm text-gray-400">
                  <Cpu size={14} className="text-aura-blue" />
                  Blueprint Output
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white transition-colors"
                >
                  {copied ? <Check size={13} className="text-green-400" /> : <Copy size={13} />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
              <pre className="font-mono text-xs text-gray-300 leading-relaxed whitespace-pre-wrap overflow-auto max-h-[500px]">
                {output}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
